spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/second
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true # sql이 여러 줄로 이쁘게 보여짐.
        show_sql: true # sql이 보여짐.
    open-in-view: true
  data:
    web:
      pageable:
        default-page-size: 3
        max-page-size: 2000
logging.level:
#  org.hibernate.SQL: trace
  org.hibernate.type: trace # ?가 보여짐.